# Generated by Django 4.1.1 on 2022-09-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_parlour', '0002_alter_master_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
